name: Build and deploy Mapbox StaticAssets
on:
  push:
    paths:
    - 'Ukad.UmbracoPackageMapbox.StaticAssets/**'
  workflow_dispatch:
  
jobs:
  bump-version:
    name: "Bump Version on main"
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    outputs:
      version: ${{ steps.version.outputs.newTag }}
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-node@v3"
        with:
          node-version: 16
      - name: "Bump version"
        id: version
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: ''
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PACKAGEJSON_DIR: Ukad.UmbracoPackageMapbox.StaticAssets
          
  build-and-push:
    runs-on: ubuntu-latest
    needs: [bump-version]
    if: always()
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Get current version dev
      working-directory: Ukad.UmbracoPackageMapbox.StaticAssets
      run: |
        version="$(cat package.json | grep version | awk -F ':' {'print $2'} | grep -o -P '(?<=").*(?=")')"
        echo "VERSION=$version-${GITHUB_SHA::7}" >> $GITHUB_ENV
    - name: Get current version main
      if: ${{ github.ref == 'refs/heads/main' }}
      working-directory: Ukad.UmbracoPackageMapbox.StaticAssets
      run: |
        version="$(cat package.json | grep version | awk -F ':' {'print $2'} | grep -o -P '(?<=").*(?=")')"
        echo "VERSION=$version" >> $GITHUB_ENV
    - name: Restore dependencies
      run: dotnet restore 
    - name: Build
      run: dotnet build Ukad.UmbracoPackageMapbox.StaticAssets/Ukad.UmbracoPackageMapbox.StaticAssets.csproj --configuration Release --no-restore
    - name: Pack
      run: dotnet pack Ukad.UmbracoPackageMapbox.StaticAssets/Ukad.UmbracoPackageMapbox.StaticAssets.csproj --configuration Release --output artifacts /p:Version=${{ env.VERSION }}
    - name: Push
      run: dotnet nuget push artifacts/Ukad.UmbracoPackageMapbox.StaticAssets.${{ env.VERSION }}.nupkg -k ${{ secrets.UKAD_NUGET_SRV_API_KEY }} -s https://nuget.ukad.dev/nuget/internal/ --no-symbols
